/**
 * ProjectUnderstanding (§6) — a compact, clearly-AI-labeled "What this project is
 * about" panel. It reflects the server-side enrichment read of the room's Q&A and
 * updates live as answers arrive (the store merges `enrichment.updated` events).
 *
 * Honesty is the whole point: the panel is explicitly marked AI-generated, names
 * the model, says how many answers informed it, and NEVER appears until there's a
 * real summary to show (no empty "AI is thinking" placeholder cluttering the room).
 * The owner gets a quiet "re-scan" affordance; everyone else just sees the read.
 *
 * Dark Kumo theme + brand accent by construction (via the shared ui primitives),
 * AA contrast, and all motion is reduced-motion-gated in styles.css.
 */
import { useEffect, useRef, useState } from 'react';
import { Sparkle } from '@phosphor-icons/react';
import { ArrowClockwise } from '@phosphor-icons/react';
import type { ProjectUnderstanding as Understanding } from '@ask/contracts';
import { Card, Eyebrow, Heading, Muted, relativeTime } from './components/ui';

interface Props {
  understanding: Understanding | undefined;
  /** Owner-only manual re-scan. Omit to hide the control (non-owners / off). */
  onRescan?: () => void;
  /** True while a re-scan request is in flight (disables the control + spins it). */
  rescanning?: boolean;
}

export function ProjectUnderstanding({ understanding, onRescan, rescanning = false }: Props) {
  // A subtle "updated" pulse whenever the summary's updatedAt changes live. Hooks
  // run unconditionally (before the null-guard) so the panel can appear/update safely.
  const updatedAt = understanding?.updatedAt;
  const prevUpdatedAt = useRef<string | undefined>(updatedAt);
  const [pulse, setPulse] = useState(false);
  useEffect(() => {
    if (updatedAt && prevUpdatedAt.current && updatedAt !== prevUpdatedAt.current) {
      setPulse(true);
      const t = window.setTimeout(() => setPulse(false), 1900);
      prevUpdatedAt.current = updatedAt;
      return () => window.clearTimeout(t);
    }
    prevUpdatedAt.current = updatedAt;
    return undefined;
  }, [updatedAt]);

  // No read yet → render nothing. The panel is enhancement, never a placeholder.
  if (!understanding || !understanding.summary.trim()) return null;

  const answers = understanding.basedOnAnswers;
  const basis =
    answers === 0
      ? 'from the questions so far'
      : `from ${answers} answer${answers === 1 ? '' : 's'}`;

  return (
    <Card
      as="section"
      glow
      className={['ask-enter flex flex-col gap-2.5 p-5', pulse ? 'ask-updated' : ''].join(' ')}
      aria-label="AI summary of what this project is about"
      data-testid="project-understanding"
    >
      <div className="flex items-center justify-between gap-3">
        <Eyebrow>
          <span className="inline-flex items-center gap-1.5">
            <Sparkle size={13} weight="fill" aria-hidden="true" /> AI summary · {basis}
          </span>
        </Eyebrow>
        {onRescan ? (
          <button
            type="button"
            onClick={onRescan}
            disabled={rescanning}
            data-testid="rescan-understanding"
            aria-label="Re-scan the project with AI"
            className="ask-mono inline-flex items-center gap-1.5 rounded-lg border border-white/10 px-2 py-1 text-[0.68rem] uppercase tracking-wider text-white/60 transition-colors hover:border-white/25 hover:text-white/85 disabled:cursor-not-allowed disabled:opacity-60"
          >
            <ArrowClockwise
              size={12}
              className={rescanning ? 'animate-spin' : undefined}
              aria-hidden="true"
            />
            <span className="min-w-[6ch] text-center">{rescanning ? 'Scanning…' : 'Re-scan'}</span>
          </button>
        ) : null}
      </div>

      <Heading level={2} className="text-base">
        What this project is about
      </Heading>

      {/* aria-live so a screen reader hears the refreshed summary when it changes. */}
      <div aria-live="polite">
        <Muted className="text-[0.92rem]">{understanding.summary}</Muted>
      </div>

      <p className="ask-mono text-[0.68rem] text-white/40" title={understanding.updatedAt}>
        Generated by {understanding.model} · {relativeTime(understanding.updatedAt)} · AI-written,
        may be imperfect
      </p>
    </Card>
  );
}
